/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AccessorySplashView, UIImage;

__attribute__((visibility("hidden")))
@interface AccessorySplashViewController : XXUnknownSuperclass {
	AccessorySplashView* _splashView;
}
@property(retain, nonatomic) UIImage* image;
// declared property setter: -(void)setImage:(id)image;
// declared property getter: -(id)image;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

