/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, UIImageView, UIButton, UINavigationBar, UILabel, UITabBar;

__attribute__((visibility("hidden")))
@interface AccessorySplashView : XXUnknownSuperclass {
	unsigned _imageIsExternal : 1;
	UIImageView* _imageView;
	UILabel* _label;
	UINavigationBar* _navigationBar;
	UILabel* _routeNameLabel;
	UIButton* _routePickerButton;
	UITabBar* _tabBar;
}
@property(readonly, assign, nonatomic) UILabel* routeNameLabel;
@property(readonly, assign, nonatomic) UIButton* routePickerButton;
@property(retain, nonatomic) UIImage* image;
-(id)_navBarTitle;
-(void)_availableRoutesChangedNotification:(id)notification;
-(void)_routePickerButtonAction:(id)action;
// declared property setter: -(void)setImage:(id)image;
-(void)setExternalImage:(id)image;
// declared property getter: -(id)routeNameLabel;
// declared property getter: -(id)routePickerButton;
// declared property getter: -(id)image;
-(void)layoutSubviews;
-(void)reloadRoutePickerAnimated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

