/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface MoreListTableCell : XXUnknownSuperclass {
	UIImageView* _moreImageView;
	UILabel* _moreTitleLabel;
}
@property(retain, nonatomic) UIImage* selectedMoreImage;
@property(copy, nonatomic) NSString* moreTitle;
@property(retain, nonatomic) UIImage* moreImage;
// declared property setter: -(void)setSelectedMoreImage:(id)image;
// declared property getter: -(id)selectedMoreImage;
// declared property setter: -(void)setMoreTitle:(id)title;
// declared property getter: -(id)moreTitle;
// declared property setter: -(void)setMoreImage:(id)image;
// declared property getter: -(id)moreImage;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

