/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MPTransportControlsTarget <NSObject>
@optional
-(void)transportControlsDidResize:(id)transportControls;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls releasedHeldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls heldButtonPart:(unsigned)part;
@end

