/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicCellConfiguration : XXUnknownSuperclass {
}
+(void)configureCell:(id)cell forViewController:(id)viewController withEntity:(id)entity atIndex:(unsigned)index;
+(float)expandedTableViewCellHeight;
+(float)tableViewCellHeight;
+(Class)tableViewCellClass;
+(id)tableViewBackgroundColor;
@end

