/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSArray;
@protocol MusicMoreViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MusicMoreViewController : XXUnknownSuperclass {
	id<MusicMoreViewControllerDelegate> _moreDelegate;
	UILabel* _sortDescriptionLabel;
	NSArray* _viewControllers;
}
@property(retain, nonatomic) NSArray* viewControllers;	// @synthesize=_viewControllers
@property(assign, nonatomic) id<MusicMoreViewControllerDelegate> moreDelegate;	// @synthesize=_moreDelegate
+(float)widthThatFits;
// declared property getter: -(id)viewControllers;
// declared property setter: -(void)setMoreDelegate:(id)delegate;
// declared property getter: -(id)moreDelegate;
// declared property setter: -(void)setViewControllers:(id)controllers;
-(void)_musicDefaultsDidChangeNotification:(id)_musicDefaults;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

