/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicSongCellConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicPlaylistSongCellConfiguration : MusicSongCellConfiguration {
}
+(void)configureCell:(id)cell forViewController:(id)viewController withEntity:(id)entity atIndex:(unsigned)index;
+(Class)tableViewCellClass;
@end

