/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "NSObject.h"


@protocol MusicPlaylistPanningDataSource <NSObject>
@optional
-(void)playlistGridViewDidEndPanning:(id)playlistGridView;
-(void)playlistGridView:(id)view loadImageForPanningToPoint:(CGPoint)point completionHandler:(id)handler;
-(void)playlistGridView:(id)view didBeginPanningAtPoint:(CGPoint)point;
@end

