/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface MusicStoreSocialURLResolutionOperation : XXUnknownSuperclass {
	NSString* _actionType;
	NSURL* _url;
}
@property(readonly, assign) NSURL* outputURL;
@property(readonly, assign) NSString* socialActionType;
-(void)_setOutputURL:(id)url;
-(void)run;
// declared property getter: -(id)socialActionType;
// declared property getter: -(id)outputURL;
-(void)dealloc;
-(id)initWithSocialActionType:(id)socialActionType;
-(id)init;
@end

