/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicGridViewController.h"


__attribute__((visibility("hidden")))
@interface MusicGenresViewController : MusicGridViewController {
}
-(void)gridView:(id)view didSelectViewAtIndexPath:(id)indexPath;
@end

