/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicGridConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicStandardGridConfiguration : MusicGridConfiguration {
}
+(void)configureView:(id)view forViewController:(id)viewController withEntity:(id)entity atIndexPath:(id)indexPath;
+(id)newGridView;
+(unsigned)numberOfGridColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(id)gridViewBackgroundImageName;
+(float)gridRowHeight;
+(id)gridBackgroundColor;
@end

