/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MPMediaItemImageRequest;

__attribute__((visibility("hidden")))
@interface MusicAlbumViewButton : XXUnknownSuperclass {
	MPMediaItemImageRequest* _imageRequest;
}
@property(retain, nonatomic) MPMediaItemImageRequest* imageRequest;	// @synthesize=_imageRequest
// declared property getter: -(id)imageRequest;
// declared property setter: -(void)setImageRequest:(id)request;
-(void)dealloc;
@end

