/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicGridViewDataSource.h"
#import "MusicGridViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MusicSectionHeaderView, MusicGridView, MusicQueryDataSource;

__attribute__((visibility("hidden")))
@interface MusicGridViewController : XXUnknownSuperclass <MusicGridViewDataSource, MusicGridViewDelegate> {
	MusicQueryDataSource* _dataSource;
	MusicSectionHeaderView* _globalHeaderView;
	Class _gridConfigurationClass;
	MusicGridView* _gridView;
	BOOL _reloadWhenVisible;
	BOOL _visible;
}
@property(readonly, assign, nonatomic) MusicGridView* gridView;	// @synthesize=_gridView
@property(readonly, assign, nonatomic) Class gridConfigurationClass;	// @synthesize=_gridConfigurationClass
@property(readonly, assign, nonatomic) MusicQueryDataSource* dataSource;	// @synthesize=_dataSource
// declared property getter: -(Class)gridConfigurationClass;
// declared property getter: -(id)dataSource;
-(void)_updateGlobalHeaderView;
-(void)reloadData;
// declared property getter: -(id)gridView;
-(float)topScrollInset;
-(float)globalHeaderHeight;
-(void)dataSourceDidInvalidate;
-(void)_dataSourceDidInvalidateNotification:(id)_dataSource;
-(void)gridViewWillBeginDragging:(id)gridView;
-(BOOL)isVisibleInMorePopover;
-(BOOL)shouldPrefetchArtworkForGridView:(id)gridView;
-(BOOL)showsIndexBarForGridView:(id)gridView;
-(id)localizedSectionIndexTitlesForGridView:(id)gridView;
-(unsigned)gridView:(id)view itemIndexForSectionTitleIndex:(unsigned)sectionTitleIndex;
-(CGRect)gridView:(id)view frameForSectionIndexGivenProposedFrame:(CGRect)sectionIndexGivenProposedFrame;
-(id)gridView:(id)view viewForIndexPath:(id)indexPath reusingView:(id)view3;
-(void)decodeArtworkForRow:(unsigned)row withNumberOfColumns:(unsigned)columns andNumberOfItems:(unsigned)items waitUntilDone:(BOOL)done;
-(unsigned)numberOfColumnsInGridView:(id)gridView;
-(unsigned)numberOfItemsInGridView:(id)gridView;
-(void)addAllEntitiesToPickerOverlay;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource gridConfigurationClass:(Class)aClass;
-(id)init;
@end

