/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MFMailComposeViewControllerDelegate.h"
#import "MPPlaybackControlsDelegate.h"
#import "MPTransportControlsTarget.h"
#import "MusicPlaybackControlsViewDelegate.h"
#import "Music~ipad-Structs.h"
#import "MusicSegmentedControlDelegate.h"
#import "UIPageControllerDelegate.h"

@class MusicNavigationView, UITapGestureRecognizer, MusicQueryNowPlayingItem, UIPageController, MusicQueryQueueFeeder, UIPinchGestureRecognizer, MusicNavigationTabButton, MusicSegmentedControl, MusicPlaybackControlsView;
@protocol MusicPlaybackViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MusicPlaybackViewController : XXUnknownSuperclass <MFMailComposeViewControllerDelegate, MPPlaybackControlsDelegate, MPTransportControlsTarget, MusicPlaybackControlsViewDelegate, MusicSegmentedControlDelegate, UIPageControllerDelegate> {
	id<MusicPlaybackViewControllerDelegate> _delegate;
	UITapGestureRecognizer* _doubleTapGestureRecognizer;
	MusicQueryNowPlayingItem* _item;
	MusicNavigationView* _navigationView;
	UIPageController* _pageController;
	UIPinchGestureRecognizer* _pinchGestureRecognizer;
	BOOL _playbackControlsHidden;
	MusicPlaybackControlsView* _playbackControlsView;
	MusicNavigationTabButton* _queueButton;
	MusicQueryQueueFeeder* _queueFeeder;
	MusicSegmentedControl* _segmentedControl;
	UITapGestureRecognizer* _tapGestureRecognizer;
	unsigned _visibleIndexBeforePaging;
}
@property(assign, nonatomic, getter=arePlaybackControlsHidden) BOOL playbackControlsHidden;	// @synthesize=_playbackControlsHidden
@property(retain, nonatomic) MusicSegmentedControl* segmentedControl;	// @synthesize=_segmentedControl
@property(assign, nonatomic) id<MusicPlaybackViewControllerDelegate> delegate;	// @synthesize=_delegate
// declared property getter: -(id)segmentedControl;
// declared property getter: -(BOOL)arePlaybackControlsHidden;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)_setQueueFeeder:(id)feeder;
-(void)_setItem:(id)item;
-(CGRect)_pageControllerFrame;
// declared property setter: -(void)setSegmentedControl:(id)control;
-(void)setPlaybackControlsHidden:(BOOL)hidden animation:(int)animation;
// declared property setter: -(void)setPlaybackControlsHidden:(BOOL)hidden;
-(void)_itemDidChangeNotification:(id)_item;
-(void)_viewDidRecognizePinch:(id)_view;
-(void)_viewDidRecognizeDoubleTap:(id)_view;
-(void)_viewDidRecognizeTap:(id)_view;
-(void)_selectedSegmentIndexDidChange:(id)_selectedSegmentIndex;
-(void)_queueButtonAction:(id)action;
-(void)_backButtonAction:(id)action;
-(void)musicSegmentedControlDidSelectMoreItem:(id)musicSegmentedControl;
-(void)playbackControlsViewRequestsTransitionToNowPlaying:(id)nowPlaying;
-(unsigned)shuffleTypeForPlaybackControls:(id)playbackControls;
-(unsigned)repeatTypeForPlaybackControls:(id)playbackControls;
-(BOOL)controlsOverlay:(id)overlay shouldDisableMailPodcastLinkButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideMailPodcastLinkButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didClickMailPodcastLinkButtonForItem:(id)item;
-(unsigned)controlsOverlay:(id)overlay playbackSpeedForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldDisablePlaybackSpeedButtonForItem:(id)item;
-(void)controlsOverlayDidClickPlaybackSpeedButton:(id)controlsOverlay;
-(BOOL)controlsOverlay:(id)overlay shouldDisableRewindButtonForItem:(id)item;
-(void)controlsOverlayDidClickRewindButton:(id)controlsOverlay;
-(BOOL)controlsOverlay:(id)overlay shouldSelectSocialLikeButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideSocialPostButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideSocialLikeButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didTapSocialPostButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didTapSocialLikeButtonForItem:(id)item;
-(BOOL)playbackControlsDidTapGeniusButton:(id)playbackControls;
-(BOOL)playbackControls:(id)controls changedShuffleType:(unsigned)type;
-(BOOL)playbackControls:(id)controls changedRepeatType:(unsigned)type;
-(BOOL)hideGeniusButtonForPlaybackControls:(id)playbackControls;
-(BOOL)transportControls:(id)controls releasedHeldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls heldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned)part;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)pageControllerDidEndPaging:(id)pageController;
-(void)pageControllerWillBeginPaging:(id)pageController;
-(id)pageController:(id)controller viewControllerAtIndex:(int)index;
-(BOOL)isStatusBarHidden;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidUnload;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

