/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicQueryQueueFeeder.h"

@protocol MusicGeniusMixQueueFeederDataSource;

__attribute__((visibility("hidden")))
@interface MusicGeniusMixQueueFeeder : MusicQueryQueueFeeder {
	unsigned _currentPlaylistOffset;
	id<MusicGeniusMixQueueFeederDataSource> _dataSource;
}
@property(retain, nonatomic) id<MusicGeniusMixQueueFeederDataSource> dataSource;	// @synthesize=_dataSource
// declared property getter: -(id)dataSource;
-(BOOL)_configureWithMix:(id)mix playbackContext:(id)context startPlayback:(BOOL)playback;
// declared property setter: -(void)setDataSource:(id)source;
-(void)shuffleItemsWithAnchor:(unsigned*)anchor;
-(id)mediaItemAtIndex:(unsigned)index;
-(unsigned)indexOfMediaItem:(id)mediaItem;
-(id)query;
-(BOOL)reloadWithPlaybackContext:(id)playbackContext keepPlayingCurrentItemIfPossible:(BOOL)possible;
-(BOOL)reloadWithDataSource:(id)dataSource keepPlayingCurrentItemIfPossible:(BOOL)possible;
-(unsigned)realRepeatType;
-(id)localizedPositionInPlaylistString:(id)playlistString;
-(void)restoreAVControllerPlaybackQueue:(id)queue fromUnarchiver:(id)unarchiver;
-(void)archiveAVControllerPlaybackQueue:(id)queue toArchiver:(id)archiver;
-(id)pathAtIndex:(unsigned)index;
-(unsigned)numberOfPaths;
-(unsigned)itemCount;
-(void)dealloc;
@end

