/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicVolumeSlider : XXUnknownSuperclass {
	int _musicStyle;
}
@property(assign, nonatomic) int musicStyle;	// @synthesize=_musicStyle
// declared property getter: -(int)musicStyle;
// declared property setter: -(void)setMusicStyle:(int)style;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(id)initWithFrame:(CGRect)frame;
@end

