/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MPMediaItem;

__attribute__((visibility("hidden")))
@interface MusicQueryNowPlayingItem : XXUnknownSuperclass {
	MPMediaItem* _mediaItem;
}
@property(readonly, assign, nonatomic) MPMediaItem* mediaItem;	// @synthesize=_mediaItem
@property(assign) double playbackCheckpointCurrentTime;	// converted property
+(id)_imageCache;
// declared property getter: -(id)mediaItem;
-(id)_newTimeMarkersForChapterType:(int)chapterType;
-(void)_handlePlaybackFinishedTime:(double)time finishedByHittingEnd:(BOOL)end;
-(id)_chapterTitleForTime:(double)time;
-(void)_defaultsDidChangeNotification;
-(unsigned long long)persistentID;
-(void)setRating:(float)rating;
-(float)userRating;
-(BOOL)useEmbeddedChapterData;
-(id)urlTimeMarkers;
-(unsigned)type;
-(id)titlesForTime:(double)time;
-(void)setupPlaybackInfo;
-(void)setPlaybackStoppedTime:(double)time;
-(void)setPlaybackFinishedTime:(double)time;
// converted property setter: -(void)setPlaybackCheckpointCurrentTime:(double)time;
-(void)_updateBookmarkTimeIfNecessary:(double)necessary;
-(void)pushBookmarkingTimesToCloud;
// converted property getter: -(double)playbackCheckpointCurrentTime;
-(void)notePlaybackFinishedByHittingEnd;
-(id)mainTitle;
-(id)imageCacheRequestWithSize:(CGSize)size time:(double)time;
-(BOOL)hasDataForItemArtwork;
-(BOOL)hasDisplayableText;
-(id)genre;
-(BOOL)isStreamable;
-(BOOL)isSupportedDefaultPlaybackSpeed:(unsigned)speed;
-(BOOL)isAssetURLValid;
-(BOOL)isPlaceholderForItem:(id)item;
-(BOOL)isValidPlayerSubstituteForItem:(id)item;
-(double)durationFromExternalMetadata;
-(id)displayableText;
-(unsigned)discCount;
-(unsigned)discNumber;
-(float)defaultPlaybackRate;
-(id)composer;
-(id)chapterTimeMarkers;
-(id)artworkTimeMarkers;
-(id)artworkMIMEType;
-(id)artworkImageData;
-(void)applyVolumeNormalizationForQueuedItems:(id)queuedItems;
-(unsigned)albumTrackCount;
-(unsigned)albumTrackNumber;
-(id)albumArtist;
-(id)artist;
-(id)album;
-(void)loadAssetAndPlayerItem;
-(id)description;
-(void)dealloc;
-(id)initWithMediaItem:(id)mediaItem;
@end

