/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, NSTimer, UIProgressView, UILabel;

__attribute__((visibility("hidden")))
@interface MusicNoContentView : XXUnknownSuperclass {
	UIImageView* _cloudImageView;
	NSTimer* _cloudProgressTimer;
	UIProgressView* _cloudProgressView;
	UILabel* _subtitleLabel;
	UILabel* _titleLabel;
}
-(id)_newTitleLabel;
-(id)_newSubtitleLabel;
-(id)_newProgressView;
-(void)_updateProgressTimer:(id)timer;
-(void)_isCloudUpdateInProgressDidChangeNotification:(id)_isCloudUpdateInProgress;
-(void)didMoveToSuperview;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

