/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MFMailComposeViewControllerDelegate.h"
#import "MPPlaybackControlsDelegate.h"
#import "MPTransportControlsTarget.h"
#import "MusicPickerOverlayDelegate.h"
#import "MusicPlaybackControlsViewDelegate.h"
#import "Music~ipad-Structs.h"
#import "UITextFieldDelegate.h"

@class MusicPickerOverlay, MusicNavigationView, UIView, UIViewController, UIImageView, UIButton, MusicSegmentedControl, MusicNoContentView, MusicPlaybackControlsView;
@protocol MusicBrowserViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MusicBrowserViewController : XXUnknownSuperclass <MFMailComposeViewControllerDelegate, MPPlaybackControlsDelegate, MPTransportControlsTarget, MusicPickerOverlayDelegate, MusicPlaybackControlsViewDelegate, UITextFieldDelegate> {
	UIView* _containerView;
	UIViewController* _contentViewController;
	id<MusicBrowserViewControllerDelegate> _delegate;
	MusicNavigationView* _navigationView;
	MusicNoContentView* _noContentView;
	MusicPickerOverlay* _pickerOverlay;
	UIView* _pickerOverlayBackstop;
	BOOL _playbackControlsHidden;
	MusicPlaybackControlsView* _playbackControlsView;
	UIViewController* _savedContentViewController;
	MusicSegmentedControl* _savedSegmentedControl;
	MusicSegmentedControl* _segmentedControl;
	UIImageView* _woodLeftImageView;
	UIImageView* _woodRightImageView;
}
@property(retain, nonatomic) MusicSegmentedControl* segmentedControl;	// @synthesize=_segmentedControl
@property(assign, nonatomic, getter=arePlaybackControlsHidden) BOOL playbackControlsHidden;	// @synthesize=_playbackControlsHidden
@property(retain, nonatomic) UIButton* leftButton;
@property(retain, nonatomic) UIViewController* contentViewController;
@property(assign, nonatomic) id<MusicBrowserViewControllerDelegate> delegate;	// @synthesize=_delegate
// declared property getter: -(id)segmentedControl;
// declared property getter: -(BOOL)arePlaybackControlsHidden;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)_updateNoContentView;
-(void)_showSearchViewControllerIfNecessary;
-(BOOL)_libraryHasContent;
-(void)_hideSearchViewControllerIfNecessary;
-(CGRect)_contentViewControllerFrame;
// declared property setter: -(void)setSegmentedControl:(id)control;
-(void)setPlaybackControlsHidden:(BOOL)hidden animation:(int)animation;
// declared property setter: -(void)setPlaybackControlsHidden:(BOOL)hidden;
-(void)setLeftButton:(id)button animated:(BOOL)animated;
// declared property setter: -(void)setLeftButton:(id)button;
// declared property getter: -(id)leftButton;
-(void)setContentViewController:(id)controller animation:(int)animation completionHandler:(id)handler;
// declared property setter: -(void)setContentViewController:(id)controller;
// declared property getter: -(id)contentViewController;
-(void)_accessorySplashViewWillAppearNotification:(id)_accessorySplashView;
-(void)_searchFieldTextDidChangeNotification:(id)_searchFieldText;
-(void)_mediaLibraryDidChangeNotification:(id)_mediaLibrary;
-(void)_availableMediaLibrariesDidChangeNotification:(id)_availableMediaLibraries;
-(void)_applicationDidBecomeActiveNotification:(id)_application;
-(void)playbackControlsViewRequestsTransitionToNowPlaying:(id)nowPlaying;
-(void)pickerOverlayRequestsFinish:(id)finish;
-(unsigned)shuffleTypeForPlaybackControls:(id)playbackControls;
-(unsigned)repeatTypeForPlaybackControls:(id)playbackControls;
-(BOOL)controlsOverlay:(id)overlay shouldDisableMailPodcastLinkButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideMailPodcastLinkButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didClickMailPodcastLinkButtonForItem:(id)item;
-(unsigned)controlsOverlay:(id)overlay playbackSpeedForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldDisablePlaybackSpeedButtonForItem:(id)item;
-(void)controlsOverlayDidClickPlaybackSpeedButton:(id)controlsOverlay;
-(BOOL)controlsOverlay:(id)overlay shouldDisableRewindButtonForItem:(id)item;
-(void)controlsOverlayDidClickRewindButton:(id)controlsOverlay;
-(BOOL)controlsOverlay:(id)overlay shouldSelectSocialLikeButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideSocialPostButtonForItem:(id)item;
-(BOOL)controlsOverlay:(id)overlay shouldHideSocialLikeButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didTapSocialPostButtonForItem:(id)item;
-(void)controlsOverlay:(id)overlay didTapSocialLikeButtonForItem:(id)item;
-(BOOL)playbackControlsDidTapGeniusButton:(id)playbackControls;
-(BOOL)playbackControls:(id)controls changedShuffleType:(unsigned)type;
-(BOOL)playbackControls:(id)controls changedRepeatType:(unsigned)type;
-(BOOL)hideGeniusButtonForPlaybackControls:(id)playbackControls;
-(BOOL)transportControls:(id)controls releasedHeldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls heldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned)part;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)presentPickerOverlay:(id)overlay;
-(void)dismissPickerOverlay;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLayoutSubviews;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(BOOL)_canReloadView;
-(void)dealloc;
-(id)init;
@end

