/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicGridViewController.h"


__attribute__((visibility("hidden")))
@interface MusicArtistsViewController : MusicGridViewController {
}
+(id)persistentIDProperty;
+(id)itemPersistentIDProperty;
+(int)groupingType;
-(void)defaultsDidChange;
-(void)_appDefaultsDidChangeNotification:(id)_appDefaults;
-(void)gridView:(id)view didSelectViewAtIndexPath:(id)indexPath;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource gridConfigurationClass:(Class)aClass;
@end

