/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface MusicGenreImageRequest : XXUnknownSuperclass {
	NSString* _imageName;
}
+(id)_imageNameForGenreName:(id)genreName;
-(id)placeholderImage;
-(id)description;
-(id)copyRawImageReturningError:(id*)error;
-(id)copyImageFromImage:(id)image;
-(void)dealloc;
-(id)initWithGenreName:(id)genreName;
@end

