/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicQueryDataSource.h"

@class MPMediaPlaylist, MPMediaLibrary;

__attribute__((visibility("hidden")))
@interface MusicPlaylistSongsDataSource : MusicQueryDataSource {
	MPMediaLibrary* _mediaLibrary;
}
@property(readonly, assign, nonatomic) MPMediaPlaylist* playlist;
-(id)_mutableEntities;
// declared property getter: -(id)playlist;
-(void)moveItemFromIndex:(unsigned)index toIndex:(unsigned)index2;
-(void)removeEntityAtIndex:(unsigned)index;
-(void)_mediaLibraryDynamicPropertiesDidChangeNotification:(id)_mediaLibraryDynamicProperties;
-(BOOL)showsEntityCountFooter;
-(BOOL)allowsDownloadingAllEntities;
-(void)dealloc;
-(id)initWithQuery:(id)query entityType:(int)type;
@end

