/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Music~ipad-Structs.h"

@class MusicAVPlayer;

__attribute__((visibility("hidden")))
@interface MusicNowPlayingObserver : XXUnknownSuperclass {
	MusicAVPlayer* _avPlayer;
	dispatch_queue_s* _queue;
}
-(void)_postNowPlayingInfo;
-(void)_crossedTimeMarkerNotification:(id)notification;
-(void)_timeDidJumpNotification:(id)_time;
-(void)_rateDidChangeNotification:(id)_rate;
-(void)_playbackStateDidChangeNotification:(id)_playbackState;
-(void)_itemDidChangeNotification:(id)_item;
-(void)dealloc;
-(id)initWithMusicAVPlayer:(id)musicAVPlayer;
@end

