/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicDetailSlider : XXUnknownSuperclass {
	BOOL _active;
	int _musicStyle;
}
@property(assign, nonatomic) int musicStyle;	// @synthesize=_musicStyle
@property(assign, nonatomic) BOOL active;	// @synthesize=_active
+(Class)labelClass;
// declared property getter: -(int)musicStyle;
// declared property getter: -(BOOL)active;
// declared property setter: -(void)setMusicStyle:(int)style;
-(float)timeLabelVerticalOffsetForStyle:(int)style;
-(id)timeLabelTextColorForStyle:(int)style;
-(CGSize)timeLabelShadowOffsetForStyle:(int)style;
-(id)timeLabelShadowColorForStyle:(int)style;
-(id)timeLabelFontForStyle:(int)style;
// declared property setter: -(void)setActive:(BOOL)active;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame style:(int)style maxTrackWidth:(float)width;
@end

