/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface MusicGlowLabel : XXUnknownSuperclass {
	UIColor* _glowColor;
	float _glowRadius;
}
@property(assign, nonatomic) float glowRadius;	// @synthesize=_glowRadius
@property(retain, nonatomic) UIColor* glowColor;	// @synthesize=_glowColor
// declared property getter: -(float)glowRadius;
// declared property getter: -(id)glowColor;
// declared property setter: -(void)setGlowRadius:(float)radius;
// declared property setter: -(void)setGlowColor:(id)color;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

