/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicPlaylistSongTableViewCell.h"


__attribute__((visibility("hidden")))
@interface MusicGenreSongTableViewCell : MusicPlaylistSongTableViewCell {
}
+(void)initialize;
-(id)fontForLabelAtIndex:(unsigned)index;
@end

