/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface MusicAlbumSquareCoverView : XXUnknownSuperclass {
	UIImage* _image;
}
@property(retain, nonatomic) UIImage* image;	// @synthesize=_image
// declared property getter: -(id)image;
-(void)drawRect:(CGRect)rect;
// declared property setter: -(void)setImage:(id)image;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

