/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicTransportControls : XXUnknownSuperclass {
	int _interfaceOrientation;
	int _style;
}
@property(assign, nonatomic) int style;	// @synthesize=_style
@property(assign, nonatomic) int interfaceOrientation;	// @synthesize=_interfaceOrientation
+(Class)buttonClass;
// declared property getter: -(int)style;
// declared property getter: -(int)interfaceOrientation;
// declared property setter: -(void)setStyle:(int)style;
// declared property setter: -(void)setInterfaceOrientation:(int)orientation;
-(void)sizeToFit;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)_layoutSubviewsInLandscape;
-(void)_layoutSubviewsInPortrait;
-(void)layoutSubviews;
-(void)reloadForAdditions:(id)additions removals:(id)removals animate:(BOOL)animate;
-(id)newButtonForPart:(unsigned)part;
-(id)highlightedButtonImageForPart:(unsigned)part;
-(id)buttonImageForPart:(unsigned)part;
-(id)initWithFrame:(CGRect)frame;
@end

