/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIButton, UIActivityIndicatorView, UILabel;

__attribute__((visibility("hidden")))
@interface MusicTableFooterView : XXUnknownSuperclass {
	UIActivityIndicatorView* _activityIndicator;
	BOOL _activityIndicatorHidden;
	UIButton* _downloadAllButton;
	UILabel* _titleLabel;
}
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) UIButton* downloadAllButton;	// @synthesize=_downloadAllButton
@property(assign, nonatomic) BOOL activityIndicatorHidden;	// @synthesize=_activityIndicatorHidden
// declared property getter: -(id)downloadAllButton;
// declared property getter: -(BOOL)activityIndicatorHidden;
// declared property setter: -(void)setTitle:(id)title;
// declared property getter: -(id)title;
// declared property setter: -(void)setDownloadAllButton:(id)button;
// declared property setter: -(void)setActivityIndicatorHidden:(BOOL)hidden;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

