/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicPlaylistSongTableViewCell.h"


__attribute__((visibility("hidden")))
@interface MusicAlbumBacksideTableViewCell : MusicPlaylistSongTableViewCell {
}
-(id)topSeparatorColor;
-(id)shadowColorForLabelAtIndex:(unsigned)index;
-(void)layoutSubviews;
-(BOOL)isPlaying;
-(CGRect)frameForLabelAtIndex:(unsigned)index;
-(id)fontForLabelAtIndex:(unsigned)index;
-(void)drawForegroundInRect:(CGRect)rect selected:(BOOL)selected;
-(void)drawBackgroundInRect:(CGRect)rect;
-(id)colorForLabelAtIndex:(unsigned)index selected:(BOOL)selected;
-(id)bottomSeparatorColor;
-(id)backgroundColor;
@end

