/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MusicSegmentedViewController, NSString;

__attribute__((visibility("hidden")))
@interface MusicSearchViewController : XXUnknownSuperclass {
	NSString* _searchString;
	MusicSegmentedViewController* _segmentedViewController;
}
@property(copy, nonatomic) NSString* searchString;	// @synthesize=_searchString
@property(readonly, assign, nonatomic) MusicSegmentedViewController* segmentedViewController;	// @synthesize=_segmentedViewController
// declared property getter: -(id)searchString;
// declared property setter: -(void)setSearchString:(id)string;
// declared property getter: -(id)segmentedViewController;
-(void)viewDidUnload;
-(void)loadView;
-(void)dealloc;
@end

