/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicExpandedCellButton : XXUnknownSuperclass {
	int _buttonType;
}
@property(readonly, assign, nonatomic) float _idealWidth;
+(id)expandedCellButtonWithType:(int)type;
// declared property getter: -(float)_idealWidth;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(id)initWithType:(int)type;
@end

