/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicPickerOverlay.h"

@class MPMediaItem;

__attribute__((visibility("hidden")))
@interface MusicGeniusPickerOverlay : MusicPickerOverlay {
	MPMediaItem* _pickedItem;
}
-(void)viewController:(id)controller didPickEntity:(id)entity;
-(id)title;
-(id)rightButtons;
-(id)dismissButton;
-(void)loadViewController;
-(void)finish;
-(void)dealloc;
@end

