/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicStandardGridView.h"


__attribute__((visibility("hidden")))
@interface MusicGenreGridView : MusicStandardGridView {
}
@property(assign, nonatomic, getter=_shouldUseSubviews, setter=_setShouldUseSubviews:) BOOL shouldUseSubviews;	// @dynamic
@end

