/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicGridConfiguration : XXUnknownSuperclass {
}
+(BOOL)shouldPrefetchArtwork;
+(void)decodeArtworkForEntities:(id)entities waitUntilDone:(BOOL)done;
+(void)configureView:(id)view forViewController:(id)viewController withEntity:(id)entity atIndexPath:(id)indexPath;
+(id)newGridView;
+(unsigned)numberOfGridColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(float)gridRowHeight;
+(id)gridBackgroundColor;
@end

