/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MusicPlaybackView, MusicAlbumBacksideViewController, MusicQueryNowPlayingItem;

__attribute__((visibility("hidden")))
@interface MusicPlaybackItemViewController : XXUnknownSuperclass {
	MusicAlbumBacksideViewController* _backsideTableViewController;
	BOOL _flipped;
	MusicQueryNowPlayingItem* _item;
	MusicPlaybackView* _playbackView;
}
@property(readonly, assign, nonatomic, getter=isFlipped) BOOL flipped;	// @synthesize=_flipped
@property(retain, nonatomic) MusicQueryNowPlayingItem* item;	// @synthesize=_item
+(id)_imageCache;
// declared property getter: -(id)item;
// declared property getter: -(BOOL)isFlipped;
-(void)_updateArtworkForPlaybackTime:(double)playbackTime;
// declared property setter: -(void)setItem:(id)item;
-(void)flipAnimated:(BOOL)animated completionHandler:(id)handler;
-(void)_displayValuesDidChangeNotification:(id)_displayValues;
-(void)_crossedTimeMarkerNotification:(id)notification;
-(void)viewDidUnload;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

