/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicQueryDataSource.h"
#import "Music~ipad-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface MusicPlaylistsDataSource : MusicQueryDataSource {
	BOOL _hasParentPlaylist;
	NSArray* _playlists;
}
-(void)_networkTypeDidChangeNotification:(id)_networkType;
-(BOOL)showsIndexBar;
-(void)invalidate;
-(BOOL)entityIsNowPlayingAtIndex:(unsigned)index;
-(id)entities;
-(void)dealloc;
-(id)initWithQuery:(id)query entityType:(int)type;
@end

