/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CALayer, NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface MusicTitlesView : XXUnknownSuperclass {
	UILabel* _albumLabel;
	UILabel* _artistLabel;
	float _idealWidth;
	BOOL _marqueeEnabled;
	UIImageView* _marqueeView;
	CALayer* _maskLayer;
	UILabel* _titleLabel;
	int _style;
}
@property(assign, nonatomic) int style;	// @synthesize=_style
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* artist;
@property(copy, nonatomic) NSString* album;
// declared property getter: -(int)style;
-(void)_updateMarqueeView;
-(void)_stopMarquee;
-(void)_startMarquee;
-(id)_newTitleLabel;
-(id)_newArtistAlbumLabel;
// declared property setter: -(void)setTitle:(id)title;
// declared property getter: -(id)title;
// declared property setter: -(void)setStyle:(int)style;
// declared property setter: -(void)setArtist:(id)artist;
// declared property getter: -(id)artist;
// declared property setter: -(void)setAlbum:(id)album;
// declared property getter: -(id)album;
-(void)_applicationDidEnterBackgroundNotification:(id)_application;
-(void)_applicationDidBecomeActiveNotification:(id)_application;
-(void)didMoveToWindow;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

