/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicTableViewController.h"
#import "MusicPickerOverlayDelegate.h"

@class MusicPlaylistSongsHeaderView;

__attribute__((visibility("hidden")))
@interface MusicPlaylistSongsViewController : MusicTableViewController <MusicPickerOverlayDelegate> {
	MusicPlaylistSongsHeaderView* _headerView;
	BOOL _presentAddSongsPickerOnAppear;
}
@property(assign, nonatomic) BOOL presentAddSongsPickerOnAppear;	// @synthesize=_presentAddSongsPickerOnAppear
// declared property setter: -(void)setPresentAddSongsPickerOnAppear:(BOOL)appear;
// declared property getter: -(BOOL)presentAddSongsPickerOnAppear;
-(void)_updateSongCountAndDurationForHeaderView;
-(void)_savePlaylist;
-(void)_refreshPlaylist;
-(void)_presentAddSongsPicker;
-(id)_seedItem;
-(id)_playlistTitle;
-(id)_playlist;
-(BOOL)_allowsSave;
-(BOOL)_allowsRefresh;
-(BOOL)_allowsAddingSongs;
-(BOOL)_allowsEditing;
-(BOOL)_allowsIndividualTrackDeletion;
-(void)_mediaLibraryDidChangeNotification:(id)_mediaLibrary;
-(void)_editDoneButtonAction:(id)action;
-(void)_backButtonAction:(id)action;
-(void)_refreshButtonAction:(id)action;
-(void)_addSongsButtonAction:(id)action;
-(void)_saveButtonAction:(id)action;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)loadView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource cellConfigurationClass:(Class)aClass;
@end

