/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, NSString;

__attribute__((visibility("hidden")))
@interface MusicSectionHeaderView : XXUnknownSuperclass {
	int _bottomSeparatorStyle;
	UIView* _bottomSeparatorView;
	int _textAlignment;
	NSString* _title;
}
@property(assign, nonatomic) int bottomSeparatorStyle;	// @synthesize=_bottomSeparatorStyle
@property(assign, nonatomic) int textAlignment;	// @synthesize=_textAlignment
@property(readonly, assign, nonatomic) NSString* title;	// @synthesize=_title
// declared property getter: -(id)title;
// declared property setter: -(void)setTextAlignment:(int)alignment;
// declared property getter: -(int)textAlignment;
// declared property getter: -(int)bottomSeparatorStyle;
// declared property setter: -(void)setBottomSeparatorStyle:(int)style;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithTitle:(id)title;
@end

