/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, MusicNavigationBackButton, UILabel;

__attribute__((visibility("hidden")))
@interface MusicArtistAlbumsHeaderView : XXUnknownSuperclass {
	MusicNavigationBackButton* _backButton;
	NSArray* _rightButtons;
	UILabel* _titleLabel;
}
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) NSArray* rightButtons;	// @synthesize=_rightButtons
@property(copy, nonatomic) NSString* backButtonTitle;
// declared property getter: -(id)rightButtons;
// declared property setter: -(void)setTitle:(id)title;
// declared property getter: -(id)title;
// declared property setter: -(void)setRightButtons:(id)buttons;
// declared property setter: -(void)setBackButtonTitle:(id)title;
// declared property getter: -(id)backButtonTitle;
-(void)setBackButtonTarget:(id)target action:(SEL)action forControlEvents:(unsigned)controlEvents;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

