/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol MusicSegmentedControlDelegate;

__attribute__((visibility("hidden")))
@interface MusicSegmentedControl : XXUnknownSuperclass {
	id<MusicSegmentedControlDelegate> _musicDelegate;
	int _style;
	unsigned _selectedSegmentIndexBeforeMore;
}
@property(assign, nonatomic) int style;	// @synthesize=_style
@property(assign, nonatomic) id<MusicSegmentedControlDelegate> musicDelegate;	// @synthesize=_musicDelegate
// declared property getter: -(int)style;
// declared property setter: -(void)setMusicDelegate:(id)delegate;
// declared property getter: -(id)musicDelegate;
// declared property setter: -(void)setStyle:(int)style;
-(void)revertMoreSegmentIfNecessary;
-(void)highlightMoreSegment;
-(void)_setSelectedSegmentIndex:(int)index notify:(BOOL)notify;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

