/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicCellConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicSongCellConfiguration : MusicCellConfiguration {
}
+(void)configureCell:(id)cell forViewController:(id)viewController withEntity:(id)entity atIndex:(unsigned)index;
+(id)tableViewBackgroundColor;
+(Class)tableViewCellClass;
+(float)tableViewCellHeight;
+(void)setDirectDrawingDisabled:(BOOL)disabled;
+(BOOL)directDrawingDisabled;
@end

