/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SSDownloadManagerObserver.h"
#import "MCProfileConnectionObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MusicStoreSocialHistory;

__attribute__((visibility("hidden")))
@interface MusicStoreClientController : XXUnknownSuperclass <SSDownloadManagerObserver, MCProfileConnectionObserver> {
	BOOL _isUsingNetwork;
	BOOL _socialEnabled;
	MusicStoreSocialHistory* _socialHistory;
}
@property(readonly, assign, nonatomic) MusicStoreSocialHistory* socialHistory;	// @synthesize=_socialHistory
@property(readonly, assign, nonatomic, getter=isSocialEnabled) BOOL socialEnabled;
+(id)sharedController;
+(id)musicStoreURLWithAction:(id)action;
// declared property getter: -(id)socialHistory;
-(void)_reloadSocialEnabled;
-(void)_networkTypeChangedNotification:(id)notification;
-(void)bagDidLoadNotification:(id)bag;
-(void)_accountStoreChangedNotification:(id)notification;
-(void)downloadManagerNetworkUsageDidChange:(id)downloadManagerNetworkUsage;
-(void)profileConnectionDidReceiveRestrictionChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)becomeActive;
// declared property getter: -(BOOL)isSocialEnabled;
-(void)dealloc;
-(id)initWithClientIdentifier:(id)clientIdentifier;
-(id)init;
@end

