/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSString, UIImageView, UIButton, NSURL, MPMediaItemImageRequest;

__attribute__((visibility("hidden")))
@interface MusicPlaybackView : XXUnknownSuperclass {
	UIImageView* _albumView;
	UIButton* _chapterButton;
	NSString* _chapterTitle;
	NSURL* _chapterURL;
	MPMediaItemImageRequest* _imageRequest;
}
@property(retain, nonatomic) MPMediaItemImageRequest* imageRequest;	// @synthesize=_imageRequest
@property(retain, nonatomic) UIImage* image;
@property(copy, nonatomic) NSURL* chapterURL;	// @synthesize=_chapterURL
@property(copy, nonatomic) NSString* chapterTitle;	// @synthesize=_chapterTitle
// declared property getter: -(id)imageRequest;
// declared property getter: -(id)chapterURL;
// declared property getter: -(id)chapterTitle;
-(void)_updateChapterButton;
// declared property setter: -(void)setImageRequest:(id)request;
// declared property setter: -(void)setImage:(id)image;
// declared property getter: -(id)image;
// declared property setter: -(void)setChapterURL:(id)url;
// declared property setter: -(void)setChapterTitle:(id)title;
-(void)_openChapterURLAction:(id)action;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

