/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicSearchField : XXUnknownSuperclass {
}
-(id)_backgroundImage;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(BOOL)_shouldSendContentChangedNotificationsIfOnlyMarkedTextChanged;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(void)sizeToFit;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawTextInRect:(CGRect)rect;
-(void)drawPlaceholderInRect:(CGRect)rect;
-(CGRect)clearButtonRectForBounds:(CGRect)bounds;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

