/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicQueryDataSource.h"
#import "Music~ipad-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface MusicArtistAlbumsDataSource : MusicQueryDataSource {
	NSArray* _albums;
	NSArray* _items;
}
@property(readonly, assign, nonatomic) NSArray* albums;
-(id)_queryForEntityAtIndex:(unsigned)index queryRelativeIndex:(out unsigned*)index2;
// declared property getter: -(id)albums;
-(BOOL)showsIndexBar;
-(id)playbackContextForIndex:(unsigned)index;
-(void)invalidate;
-(BOOL)entityIsNowPlayingAtIndex:(unsigned)index;
-(id)entities;
-(void)dealloc;
@end

