/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MusicPlaybackViewControllerDelegate <NSObject>
@optional
-(void)playbackViewControllerDidRequestExit:(id)playbackViewController;
-(void)playbackViewControllerDidSelectMoreViewController:(id)playbackViewController;
-(void)playbackViewController:(id)controller didSelectViewControllerAtIndex:(unsigned)index;
@end

