/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface MusicHeaderView : XXUnknownSuperclass {
	UILabel* _label;
	UIButton* _leftButton;
	UILabel* _subtitleLabel;
	NSArray* _rightButtons;
}
@property(readonly, assign, nonatomic) float scrollInset;
@property(copy, nonatomic) NSArray* rightButtons;	// @synthesize=_rightButtons
@property(retain, nonatomic) UIButton* leftButton;	// @synthesize=_leftButton
@property(copy, nonatomic) NSString* subtitle;
@property(copy, nonatomic) NSString* title;
// declared property getter: -(id)rightButtons;
// declared property getter: -(id)leftButton;
// declared property setter: -(void)setTitle:(id)title;
// declared property getter: -(id)title;
// declared property setter: -(void)setSubtitle:(id)subtitle;
// declared property getter: -(id)subtitle;
// declared property getter: -(float)scrollInset;
// declared property setter: -(void)setRightButtons:(id)buttons;
// declared property setter: -(void)setLeftButton:(id)button;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

