/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicQueryPlaybackContext.h"
#import "MusicGeniusMixQueueFeederDataSource.h"

@class MPMediaQueryShuffledItems, MPGeniusMix, MPMediaItem;

__attribute__((visibility("hidden")))
@interface MusicCloudGeniusMixPlaybackContext : MusicQueryPlaybackContext <MusicGeniusMixQueueFeederDataSource> {
	MPMediaQueryShuffledItems* _items;
	MPGeniusMix* _mix;
	MPMediaItem* _requiredInitialMediaItem;
}
@property(retain, nonatomic) MPMediaItem* requiredInitialMediaItem;	// @synthesize=_requiredInitialMediaItem
@property(readonly, assign, nonatomic) MPGeniusMix* mix;	// @synthesize=_mix
+(Class)queueFeederClass;
// declared property setter: -(void)setRequiredInitialMediaItem:(id)item;
// declared property getter: -(id)requiredInitialMediaItem;
// declared property getter: -(id)mix;
-(unsigned)geniusMixQueueFeeder:(id)feeder indexOfMediaItem:(id)mediaItem;
-(id)geniusMixQueueFeeder:(id)feeder queryForMediaItemAtIndex:(unsigned)index;
-(id)geniusMixQueueFeeder:(id)feeder mediaItemAtIndex:(unsigned)index;
-(unsigned)geniusMixQueueFeederMediaItemCount:(id)count;
-(void)dealloc;
-(id)initWithGeniusMix:(id)geniusMix requiredInitialMediaItem:(id)item error:(id*)error;
@end

