/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicGridViewTableViewCell : XXUnknownSuperclass {
	BOOL _automaticLayoutDisabled;
	unsigned _numberOfColumns;
}
@property(assign, nonatomic) unsigned numberOfColumns;	// @synthesize=_numberOfColumns
@property(assign, nonatomic) BOOL automaticLayoutDisabled;	// @synthesize=_automaticLayoutDisabled
// declared property getter: -(unsigned)numberOfColumns;
// declared property setter: -(void)setAutomaticLayoutDisabled:(BOOL)disabled;
// declared property getter: -(BOOL)automaticLayoutDisabled;
-(void)setNumberOfColumns:(unsigned)columns animated:(BOOL)animated;
// declared property setter: -(void)setNumberOfColumns:(unsigned)columns;
-(void)setGridView:(id)view atIndex:(unsigned)index animated:(BOOL)animated;
-(id)gridViewAtIndex:(unsigned)index;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

