/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MusicGeniusMixQueueFeederDataSource <NSObject>
-(unsigned)geniusMixQueueFeeder:(id)feeder indexOfMediaItem:(id)mediaItem;
-(id)geniusMixQueueFeeder:(id)feeder queryForMediaItemAtIndex:(unsigned)index;
-(id)geniusMixQueueFeeder:(id)feeder mediaItemAtIndex:(unsigned)index;
-(unsigned)geniusMixQueueFeederMediaItemCount:(id)count;
@end

