/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface MusicLabel : XXUnknownSuperclass {
	UIColor* _highlightedShadowColor;
	CGSize _highlightedShadowOffset;
}
@property(assign, nonatomic) CGSize highlightedShadowOffset;	// @synthesize=_highlightedShadowOffset
@property(retain, nonatomic) UIColor* highlightedShadowColor;	// @synthesize=_highlightedShadowColor
// declared property getter: -(CGSize)highlightedShadowOffset;
// declared property getter: -(id)highlightedShadowColor;
// declared property setter: -(void)setHighlightedShadowOffset:(CGSize)offset;
// declared property setter: -(void)setHighlightedShadowColor:(id)color;
-(CGSize)shadowOffset;
-(id)shadowColor;
-(void)setHighlighted:(BOOL)highlighted;
-(void)dealloc;
@end

