/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;
@protocol MusicRatingControlDelegate;

__attribute__((visibility("hidden")))
@interface MusicRatingControl : XXUnknownSuperclass {
	id<MusicRatingControlDelegate> _delegate;
	CGSize _maxHitRectPadding;
	int _rating;
	UIImageView* _starView[5];
	CGPoint _trackingStartPoint;
	CGPoint _trackingLastPoint;
	BOOL _trackingHandledDrag;
}
@property(assign, nonatomic) int rating;	// @synthesize=_rating
@property(assign, nonatomic) id<MusicRatingControlDelegate> delegate;	// @synthesize=_delegate
// declared property getter: -(int)rating;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)_updateRatingForPoint:(CGPoint)point;
-(void)_tappedAction:(id)action event:(id)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(CGSize)sizeThatFits:(CGSize)fits;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(CGRect)hitRect;
-(void)layoutSubviews;
// declared property setter: -(void)setRating:(int)rating;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

