/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, MusicAlbumSquareCoverView, UIButton;
@protocol NSObject, NSCopying;

__attribute__((visibility("hidden")))
@interface MusicArtistAlbumSectionView : XXUnknownSuperclass {
	UIButton* _downloadAllButton;
	MusicAlbumSquareCoverView* _imageView;
	id<NSObject, NSCopying> _imageRequestKey;
}
@property(retain, nonatomic) UIButton* downloadAllButton;	// @synthesize=_downloadAllButton
@property(retain, nonatomic) id<NSObject, NSCopying> imageRequestKey;	// @synthesize=_imageRequestKey
@property(retain, nonatomic) UIImage* image;
// declared property setter: -(void)setImageRequestKey:(id)key;
// declared property getter: -(id)imageRequestKey;
// declared property getter: -(id)downloadAllButton;
// declared property setter: -(void)setImage:(id)image;
// declared property getter: -(id)image;
// declared property setter: -(void)setDownloadAllButton:(id)button;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

