/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicScalingFlipViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIViewController, MusicScalingFlipView;
@protocol MusicScalingFlipViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MusicScalingFlipViewController : XXUnknownSuperclass <MusicScalingFlipViewDelegate> {
	UIView* _backgroundView;
	UIViewController* _backViewController;
	id<MusicScalingFlipViewControllerDelegate> _delegate;
	MusicScalingFlipView* _flipView;
	UIViewController* _frontViewController;
	BOOL _isFlipped;
}
@property(readonly, assign, nonatomic) MusicScalingFlipView* flipView;	// @synthesize=_flipView
@property(retain, nonatomic) UIViewController* frontViewController;	// @synthesize=_frontViewController
@property(retain, nonatomic) UIViewController* backViewController;	// @synthesize=_backViewController
@property(assign, nonatomic) id<MusicScalingFlipViewControllerDelegate> delegate;	// @synthesize=_delegate
// declared property getter: -(id)frontViewController;
// declared property getter: -(id)flipView;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
// declared property getter: -(id)backViewController;
// declared property setter: -(void)setFrontViewController:(id)controller;
// declared property setter: -(void)setBackViewController:(id)controller;
-(void)performHideForKeyboardAnimated:(BOOL)keyboardAnimated;
-(void)performFlipAnimated:(BOOL)animated;
-(void)scalingFlipViewDidRequestExit:(id)scalingFlipView;
-(void)scalingFlipViewDidFinish:(id)scalingFlipView;
-(void)viewDidUnload;
-(void)loadView;
-(void)dealloc;
@end

