/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UIViewController, NSString;
@protocol MusicPickerOverlayDelegate;

__attribute__((visibility("hidden")))
@interface MusicPickerOverlay : XXUnknownSuperclass {
@private
	id<MusicPickerOverlayDelegate> _delegate;
	UIViewController* _viewController;
	BOOL _allowMultipleEntities;
}
@property(readonly, assign, nonatomic) BOOL allowsMultipleSelections;
@property(retain, nonatomic) UIViewController* viewController;	// @synthesize=_viewController
@property(readonly, assign, nonatomic) NSString* title;
@property(readonly, assign, nonatomic) NSArray* rightButtons;
@property(assign, nonatomic) id<MusicPickerOverlayDelegate> delegate;	// @synthesize=_delegate
// declared property setter: -(void)setViewController:(id)controller;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)viewController:(id)controller didPickAllEntitiesFromDataSource:(id)dataSource;
-(void)viewController:(id)controller didPickEntity:(id)entity;
// declared property getter: -(id)viewController;
// declared property getter: -(id)title;
// declared property getter: -(BOOL)allowsMultipleSelections;
-(BOOL)shouldDisplayEntityAsDisabled:(id)disabled;
// declared property getter: -(id)rightButtons;
-(id)newAccessoryView;
-(void)loadViewController;
-(void)finish;
@end

