/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicMoreViewControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "MusicSegmentedControlDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIPopoverController, NSArray, UIViewController, MusicSegmentedControl;
@protocol MusicSegmentedViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MusicSegmentedViewController : XXUnknownSuperclass <MusicMoreViewControllerDelegate, MusicSegmentedControlDelegate, UIPopoverControllerDelegate> {
	UIViewController* _contentViewController;
	id<MusicSegmentedViewControllerDelegate> _delegate;
	UIPopoverController* _morePopoverController;
	MusicSegmentedControl* _segmentedControl;
	unsigned _selectedSegmentIndex;
	NSArray* _viewControllers;
}
@property(readonly, assign, nonatomic) MusicSegmentedControl* segmentedControl;	// @synthesize=_segmentedControl
@property(retain, nonatomic) UIViewController* selectedViewController;
@property(assign, nonatomic) unsigned selectedViewControllerIndex;
@property(assign, nonatomic) id<MusicSegmentedViewControllerDelegate> delegate;	// @synthesize=_delegate
@property(readonly, assign, nonatomic) NSArray* viewControllers;	// @synthesize=_viewControllers
// declared property getter: -(id)viewControllers;
// declared property getter: -(id)segmentedControl;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property getter: -(id)delegate;
-(void)_setSelectedViewControllerIndex:(unsigned)index allowPoppingToRoot:(BOOL)root;
-(id)_newSegmentedControl;
-(id)_moreViewControllers;
// declared property setter: -(void)setSelectedViewControllerIndex:(unsigned)index;
// declared property getter: -(unsigned)selectedViewControllerIndex;
// declared property setter: -(void)setSelectedViewController:(id)controller;
// declared property getter: -(id)selectedViewController;
-(id)newPlaybackSegmentedControl;
-(void)_defaultMediaLibraryDidChangeNotification:(id)_defaultMediaLibrary;
-(void)_availableMediaLibrariesDidChangeNotification:(id)_availableMediaLibraries;
-(void)_selectedIndexDidChange:(id)_selectedIndex;
-(void)moreViewController:(id)controller didSelectViewController:(id)controller2;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)musicSegmentedControlDidSelectMoreItem:(id)musicSegmentedControl;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(id)initWithViewControllers:(id)viewControllers;
@end

