/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Music~ipad-Structs.h"

@class NSString, MPDownloadProgressIndicator, UIImageView, UIButton, MusicExpandedCellButtonView, MPMediaDownloadObserver, UIColor;
@protocol NSObject;

__attribute__((visibility("hidden")))
@interface MusicAlbumTableViewCell : XXUnknownSuperclass {
	int _cellStyle;
	id<NSObject> _downloadableAsset;
	UIButton* _downloadButton;
	NSString* _downloadIdentifier;
	MPMediaDownloadObserver* _downloadObserver;
	MPDownloadProgressIndicator* _downloadProgressIndicator;
	int _downloadStatus;
	NSString* _duration;
	BOOL _expanded;
	MusicExpandedCellButtonView* _expandedCellButtonView;
	NSString* _index;
	int _interfaceOrientation;
	BOOL _isTemporaryCloudDownload;
	long long _itemPersistentID;
	UIImageView* _nowPlayingImageView;
	BOOL _playing;
	NSString* _title;
	UIColor* _titleColor;
}
@property(retain, nonatomic) id<NSObject> downloadableAsset;	// @synthesize=_downloadableAsset
@property(retain, nonatomic) UIColor* titleColor;	// @synthesize=_titleColor
@property(copy, nonatomic) NSString* title;	// @synthesize=_title
@property(assign, nonatomic, getter=isPlaying) BOOL playing;	// @synthesize=_playing
@property(copy, nonatomic) NSString* index;	// @synthesize=_index
@property(copy, nonatomic) NSString* duration;	// @synthesize=_duration
@property(assign, nonatomic) int interfaceOrientation;	// @synthesize=_interfaceOrientation
@property(assign, nonatomic) int cellStyle;	// @synthesize=_cellStyle
@property(assign, getter=isExpanded) BOOL expanded;	// converted property
+(void)initialize;
// declared property getter: -(id)titleColor;
// declared property getter: -(id)title;
// declared property getter: -(BOOL)isPlaying;
// declared property setter: -(void)setIndex:(id)index;
// declared property getter: -(id)index;
// declared property getter: -(int)interfaceOrientation;
// declared property getter: -(id)duration;
// declared property getter: -(id)downloadableAsset;
// declared property setter: -(void)setCellStyle:(int)style;
// declared property getter: -(int)cellStyle;
-(id)_textForLabelAtIndex:(unsigned)index;
-(int)_textAlignmentForLabelAtIndex:(unsigned)index;
-(unsigned)_numberOfLabels;
-(CGRect)_frameForLabelAtIndex:(unsigned)index;
-(id)_fontForLabelAtIndex:(unsigned)index;
-(CGRect)_nowPlayingImageViewFrame;
-(BOOL)_isDownloading;
-(CGRect)_expandedCellFrame;
-(void)_drawForegroundInRect:(CGRect)rect selected:(BOOL)selected;
-(void)_drawBackgroundInRect:(CGRect)rect;
-(CGRect)_downloadProgressIndicatorFrame;
-(CGRect)_downloadButtonFrame;
// declared property setter: -(void)setTitleColor:(id)color;
// declared property setter: -(void)setTitle:(id)title;
// declared property setter: -(void)setPlaying:(BOOL)playing;
// declared property setter: -(void)setInterfaceOrientation:(int)orientation;
// declared property setter: -(void)setDuration:(id)duration;
-(void)setDownloadIdentifier:(id)identifier downloadStatus:(int)status isTemporaryCloudDownload:(BOOL)download itemPersistentID:(long long)anId;
// declared property setter: -(void)setDownloadableAsset:(id)asset;
-(void)_downloadButtonPressed:(id)pressed;
-(void)_cancelDownloadButtonPressed:(id)pressed;
// converted property setter: -(void)setExpanded:(BOOL)expanded;
// converted property getter: -(BOOL)isExpanded;
-(void)prepareForReuse;
-(void)_drawContentInRect:(CGRect)rect selected:(BOOL)selected;
-(BOOL)drawingEnabled;
-(id)_contentString;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

