/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicArtistGridConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicComposerGridConfiguration : MusicArtistGridConfiguration {
}
+(id)titleProperty;
+(id)representativeItemPersistentIDProperty;
+(id)propertiesToFetch;
+(id)cloudStatusProperty;
+(id)artworkCacheIDProperty;
@end

