/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

__attribute__((visibility("hidden")))
@interface MusicViewController : XXUnknownSuperclass {
	UIViewController* _pushedViewController;
	UIViewController* _rootViewController;
}
@property(readonly, assign, nonatomic) UIViewController* pushedViewController;	// @synthesize=_pushedViewController
// declared property getter: -(id)pushedViewController;
-(id)popViewControllerWithAnimation:(int)animation completionHandler:(id)handler;
-(void)pushViewController:(id)controller animation:(int)animation completionHandler:(id)handler;
-(void)viewDidUnload;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(void)dealloc;
-(id)initWithRootViewController:(id)rootViewController;
-(id)init;
@end

