/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MusicPlaybackContext : XXUnknownSuperclass {
	unsigned _shuffleType;
}
@property(readonly, assign, nonatomic) unsigned realShuffleType;
@property(assign, nonatomic) unsigned shuffleType;	// @synthesize=_shuffleType
+(Class)queueFeederClass;
// declared property setter: -(void)setShuffleType:(unsigned)type;
// declared property getter: -(unsigned)shuffleType;
// declared property getter: -(unsigned)realShuffleType;
-(id)init;
@end

