/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface MusicSharedViewController : XXUnknownSuperclass {
	NSArray* _sharedMediaLibraries;
}
-(id)_sharedMediaLibraries;
-(void)_availableMediaLibrariesDidChangeNotification:(id)_availableMediaLibraries;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)accessoryType;
-(BOOL)showInlineInMorePopover;
-(BOOL)isVisibleInMorePopover;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(id)init;
@end

