/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary, NSHTTPURLResponse;

__attribute__((visibility("hidden")))
@interface MusicStoreSocialActionOperation : XXUnknownSuperclass {
	NSString* _actionType;
	unsigned long long _itemIdentifier;
	NSDictionary* _responseDictionary;
	NSHTTPURLResponse* _urlResponse;
}
@property(readonly, assign) NSHTTPURLResponse* URLResponse;
@property(readonly, assign) NSDictionary* responseDictionary;
@property(readonly, assign) NSString* socialActionType;
@property(readonly, assign) unsigned long long itemIdentifier;
-(void)_setURLResponse:(id)response;
-(void)_setResponseDictionary:(id)dictionary;
-(BOOL)_runWithActionURL:(id)actionURL error:(id*)error;
-(void)run;
// declared property getter: -(id)URLResponse;
// declared property getter: -(id)socialActionType;
// declared property getter: -(id)responseDictionary;
// declared property getter: -(unsigned long long)itemIdentifier;
-(void)dealloc;
-(id)initWithSocialActionType:(id)socialActionType itemIdentifier:(unsigned long long)identifier;
-(id)init;
@end

