/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicPlaylistPanningDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MPMediaPlaylist, NSArray;

__attribute__((visibility("hidden")))
@interface MusicPlaylistPanController : XXUnknownSuperclass <MusicPlaylistPanningDataSource> {
	float _itemPanDelta;
	NSArray* _items;
	float _panStartLocation;
	MPMediaPlaylist* _playlist;
}
@property(readonly, assign, nonatomic) MPMediaPlaylist* playlist;	// @synthesize=_playlist
// declared property getter: -(id)playlist;
-(void)playlistGridView:(id)view loadImageForPanningToPoint:(CGPoint)point completionHandler:(id)handler;
-(void)playlistGridView:(id)view didBeginPanningAtPoint:(CGPoint)point;
-(void)dealloc;
-(id)initWithPlaylist:(id)playlist;
@end

