/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Music~ipad-Structs.h"
#import "UIPopoverControllerDelegate.h"

@class UIImageView, UIButton, MusicVolumeSlider, MPAudioDeviceController, MPAudioVideoRoutingPopoverController, MusicTitlesView, MusicAlbumViewButton, MusicTransportControls;
@protocol MPPlaybackControlsDelegate, MPTransportControlsTarget, MusicPlaybackControlsViewDelegate;

__attribute__((visibility("hidden")))
@interface MusicPlaybackControlsView : XXUnknownSuperclass <UIPopoverControllerDelegate> {
	UIButton* _airplayButton;
	MusicAlbumViewButton* _albumViewButton;
	MPAudioDeviceController* _audioDeviceController;
	UIImageView* _backgroundView;
	int _interfaceOrientation;
	UIImageView* _playbackHUDView;
	MPAudioVideoRoutingPopoverController* _routePopover;
	int _style;
	MusicTitlesView* _titlesView;
	MusicTransportControls* _transportControls;
	MusicVolumeSlider* _volumeSlider;
	BOOL _wirelessRouteAvailable;
}
@property(assign, nonatomic) int style;	// @synthesize=_style
@property(assign, nonatomic) int interfaceOrientation;	// @synthesize=_interfaceOrientation
@property(assign, nonatomic) id<MPPlaybackControlsDelegate, MPTransportControlsTarget, MusicPlaybackControlsViewDelegate> delegate;
+(float)_defaultHeight;
// declared property getter: -(int)style;
// declared property getter: -(int)interfaceOrientation;
-(id)_newVolumeSlider;
-(id)_newTransportControlsView;
-(id)_newTitlesView;
-(id)_newPlaybackHUDView;
-(id)_newBackgroundView;
-(id)_newAlbumView;
-(id)_newAirPlayButton;
-(void)_initSubviews;
-(id)_imageForPlaybackSpeed:(unsigned)playbackSpeed;
// declared property setter: -(void)setStyle:(int)style;
// declared property setter: -(void)setInterfaceOrientation:(int)orientation;
-(void)preloadNextItem:(id)item;
-(void)_itemDidChangeNotification:(id)_item;
-(void)_isCloudEnabledDidChangeNotification:(id)_isCloudEnabled;
-(void)_didEnterBackgroundNotification:(id)notification;
-(void)_albumViewButtonAction:(id)action;
-(void)_airplayButtonAction:(id)action;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)audioDeviceControllerAudioRoutesChanged:(id)changed;
-(void)_layoutSubviewsInLandscape;
-(void)_layoutSubviewsInPortrait;
-(void)_layoutInvariantSubviews;
-(void)layoutSubviews;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)_updateForPlaybackSpeed;
-(void)setItem:(id)item;
// declared property setter: -(void)setDelegate:(id)delegate;
-(id)_shuffleButtonImage;
-(id)_repeatButtonImage;
-(id)newProgressIndicator;
-(id)newButtonForPart:(unsigned)part;
-(id)_mailButtonImage;
// declared property getter: -(id)delegate;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)init;
@end

