/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Music~ipad-Structs.h"

@class MusicHeaderView, MusicSectionHeaderView, NSString, NSIndexPath, NSMutableDictionary, UITableView, MusicQueryDataSource, MusicTableFooterView;

__attribute__((visibility("hidden")))
@interface MusicTableViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	Class _cellConfigurationClass;
	MusicQueryDataSource* _dataSource;
	NSString* _downloadingProgressString;
	MusicTableFooterView* _footerView;
	MusicSectionHeaderView* _globalHeaderView;
	int _ignoreDataSourceInvalidationCount;
	NSIndexPath* _indexPathForExpandedCell;
	MusicHeaderView* _musicHeaderView;
	BOOL _reloadWhenVisible;
	NSMutableDictionary* _sectionHeaderViews;
	UITableView* _tableView;
	BOOL _visible;
	int _syncAssetTotalToken;
	BOOL _syncAssetTotalTokenIsValid;
	int _syncCurrentAssetNumberToken;
	BOOL _syncCurrentAssetNumberTokenIsValid;
	unsigned _syncAssetTotal;
	unsigned _syncCurrentAssetNumber;
}
@property(readonly, assign, nonatomic) UITableView* tableView;	// @synthesize=_tableView
@property(readonly, assign, nonatomic) MusicQueryDataSource* dataSource;	// @synthesize=_dataSource
@property(readonly, assign, nonatomic) Class cellConfigurationClass;	// @synthesize=_cellConfigurationClass
// declared property getter: -(id)dataSource;
// declared property getter: -(Class)cellConfigurationClass;
-(void)_updateSyncProgressString;
-(void)_updateGlobalHeaderView;
-(void)_updateFooterView;
// declared property getter: -(id)tableView;
-(void)reloadData;
-(void)endIgnoringDataSourceInvalidation;
-(void)dataSourceDidInvalidate;
-(void)beginIgnoringDataSourceInvalidation;
-(void)_itemDidChangeNotification:(id)_item;
-(void)_dataSourceDidInvalidateNotification:(id)_dataSource;
-(void)_longPressRecognized:(id)recognized;
-(void)_downloadAllAction:(id)action;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(CGRect)tableView:(id)view frameForSectionIndexGivenProposedFrame:(CGRect)sectionIndexGivenProposedFrame;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)addAllEntitiesToPickerOverlay;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view sectionForSectionIndexTitle:(id)sectionIndexTitle atIndex:(int)index;
-(id)sectionIndexTitlesForTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)beginPlaybackForVisibleContent;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)loadView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource cellConfigurationClass:(Class)aClass;
@end

