/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface MusicExpandedCellButtonView : XXUnknownSuperclass {
	NSArray* _buttons;
	NSMutableArray* _dividers;
}
@property(copy, nonatomic) NSArray* buttons;	// @synthesize=_buttons
// declared property getter: -(id)buttons;
// declared property setter: -(void)setButtons:(id)buttons;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

