/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicTableViewController.h"

@class UIView, MusicRatingControl, MPMediaItem;

__attribute__((visibility("hidden")))
@interface MusicAlbumBacksideViewController : MusicTableViewController {
	UIView* _backgroundView;
	MPMediaItem* _item;
	MusicRatingControl* _ratingControl;
}
@property(retain, nonatomic) MPMediaItem* item;	// @synthesize=_item
// declared property getter: -(id)item;
// declared property setter: -(void)setItem:(id)item;
-(void)_mediaLibraryDidChangeNotification:(id)_mediaLibrary;
-(void)_ratingDidChange:(id)_rating;
-(void)viewDidUnload;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource cellConfigurationClass:(Class)aClass;
@end

