/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicPlaylistSongCellConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicAlbumBacksideCellConfiguration : MusicPlaylistSongCellConfiguration {
}
+(float)tableViewCellHeight;
+(Class)tableViewCellClass;
+(id)tableViewBackgroundColor;
+(void)configureCell:(id)cell forViewController:(id)viewController withEntity:(id)entity atIndex:(unsigned)index;
@end

