/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MusicHomeSharingDownloadManager;

__attribute__((visibility("hidden")))
@interface MusicApplication : XXUnknownSuperclass {
	MusicHomeSharingDownloadManager* _downloadManager;
	BOOL _extendedModeActive;
	int _extendedModeNotifyToken;
	BOOL _extendedModeNotifyTokenIsValid;
}
-(void)_disableSplashScreenSpecialCasing;
-(void)requestExtendedMode:(BOOL)mode;
-(void)_hideSplashView;
-(void)_showSplashView:(BOOL)view;
-(void)_handlePlaylistSeek:(int)seek;
-(void)_handleAlbumSeek:(int)seek;
-(void)_simpleRemoteActionNotification:(id)notification;
-(void)cancelDownloadOfAsset:(id)asset;
-(void)downloadAsset:(id)asset completionHandler:(id)handler;
-(void)sendEvent:(id)event;
-(void)dealloc;
-(id)init;
@end

