/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicSongTableViewCell.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MusicPlaylistSongTableViewCell : MusicSongTableViewCell {
	NSString* _index;
}
@property(copy, nonatomic) NSString* index;	// @synthesize=_index
+(void)initialize;
// declared property setter: -(void)setIndex:(id)index;
// declared property getter: -(id)index;
-(id)textForLabelAtIndex:(unsigned)index;
-(int)textAlignmentForLabelAtIndex:(unsigned)index;
-(unsigned)numberOfLabels;
-(CGRect)frameForLabelAtIndex:(unsigned)index;
-(id)fontForLabelAtIndex:(unsigned)index;
-(void)prepareForReuse;
-(void)dealloc;
@end

