/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicGridConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicPlaylistGridConfiguration : MusicGridConfiguration {
}
+(id)_queryForPlaylist:(id)playlist;
+(id)_newCachedImagesForPlaylistPersistentID:(unsigned long long)playlistPersistentID count:(unsigned*)count durationInMinutes:(unsigned*)minutes cacheExists:(BOOL*)exists needsRecache:(BOOL*)recache;
+(id)_iconForPlaylist:(id)playlist;
+(void)_cacheImages:(id)images forItems:(id)items count:(unsigned)count durationInMinutes:(unsigned)minutes forPlaylistPersistentID:(unsigned long long)playlistPersistentID;
+(void)configureView:(id)view forViewController:(id)viewController withEntity:(id)entity atIndexPath:(id)indexPath;
+(id)newGridView;
+(unsigned)numberOfGridColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(float)gridRowHeight;
+(id)gridBackgroundColor;
+(void)initialize;
@end

