/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Music~ipad-Structs.h"

@class UITapGestureRecognizer;
@protocol MusicGridViewDataSource, MusicGridViewDelegate;

__attribute__((visibility("hidden")))
@interface MusicGridView : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate> {
	float _gridRowHeight;
	id<MusicGridViewDataSource> _gridViewDataSource;
	id<MusicGridViewDelegate> _gridViewDelegate;
	unsigned _numberOfColumns;
	unsigned _numberOfItems;
	unsigned _lastRowRequested;
	UITapGestureRecognizer* _tapGestureRecognizer;
}
@property(assign, nonatomic) float gridRowHeight;	// @synthesize=_gridRowHeight
@property(assign, nonatomic) id<MusicGridViewDelegate> gridViewDelegate;	// @synthesize=_gridViewDelegate
@property(assign, nonatomic) id<MusicGridViewDataSource> gridViewDataSource;	// @synthesize=_gridViewDataSource
// declared property setter: -(void)setGridViewDelegate:(id)delegate;
// declared property getter: -(id)gridViewDelegate;
// declared property getter: -(id)gridViewDataSource;
// declared property getter: -(float)gridRowHeight;
-(void)_updateGridViewsForTableCell:(id)tableCell atIndexPath:(id)indexPath animated:(BOOL)animated;
-(id)viewForIndexPath:(id)indexPath;
// declared property setter: -(void)setGridViewDataSource:(id)source;
// declared property setter: -(void)setGridRowHeight:(float)height;
-(void)reloadData;
-(id)indexPathOfViewForGlobalIndex:(unsigned)globalIndex;
-(unsigned)globalIndexOfViewForIndexPath:(id)indexPath;
-(void)_viewWasTapped:(id)tapped;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(CGRect)tableView:(id)view frameForSectionIndexGivenProposedFrame:(CGRect)sectionIndexGivenProposedFrame;
-(int)tableView:(id)view sectionForSectionIndexTitle:(id)sectionIndexTitle atIndex:(int)index;
-(id)sectionIndexTitlesForTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame style:(int)style;
@end

