/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MPMediaQuery, NSArray, MPMediaLibraryConnectionAssertion, MPMediaQueryShuffledItems, MPMediaItem;

__attribute__((visibility("hidden")))
@interface MusicQueryQueueFeeder : XXUnknownSuperclass {
	MPMediaLibraryConnectionAssertion* _connectionAssertion;
	MPMediaQueryShuffledItems* _items;
	MPMediaQuery* _query;
	NSArray* _prefixMediaItems;
	MPMediaItem* _focusedItem;
	int _ignoreShuffleTypeChangesCount;
	BOOL _itemsChanged;
	BOOL _wasShuffled;
}
@property(retain, nonatomic) MPMediaItem* focusedItem;	// @synthesize=_focusedItem
@property(retain, nonatomic) NSArray* prefixMediaItems;	// @synthesize=_prefixMediaItems
@property(copy, nonatomic) MPMediaQuery* query;	// @synthesize=_query
// declared property setter: -(void)setPrefixMediaItems:(id)items;
// declared property getter: -(id)prefixMediaItems;
// declared property getter: -(id)query;
// declared property setter: -(void)setFocusedItem:(id)item;
// declared property getter: -(id)focusedItem;
-(unsigned)_shuffleItemsInFeederQueryWithShuffleType:(unsigned)shuffleType initialIndex:(unsigned)index;
-(BOOL)_reloadWithPlaybackContext:(id)playbackContext keepPlayingCurrentItemIfPossible:(BOOL)possible;
-(unsigned)unshuffledIndexOfAVItem:(id)avitem;
// declared property setter: -(void)setQuery:(id)query;
-(id)mediaItemAtIndex:(unsigned)index;
-(unsigned)indexOfMediaItem:(id)mediaItem;
-(void)_libraryDidChangeNotification:(id)_library;
-(double)bookmarkTimeForIndex:(unsigned)index;
-(id)playbackInfoAtIndex:(unsigned)index;
-(void)archiveAVControllerPlaybackQueue:(id)queue toArchiver:(id)archiver;
-(void)restoreAVControllerPlaybackQueue:(id)queue fromUnarchiver:(id)unarchiver;
-(BOOL)trackChangesCanEndPlayback;
-(void)shuffleItemsWithAnchor:(unsigned*)anchor;
-(BOOL)reloadWithDataSource:(id)dataSource keepPlayingCurrentItemIfPossible:(BOOL)possible;
-(void)_performWhileIgnoringShuffleChanges:(id)changes;
-(unsigned)realShuffleType;
-(unsigned)realRepeatType;
-(id)pathAtIndex:(unsigned)index;
-(unsigned)itemTypeForIndex:(unsigned)index;
-(Class)itemClass;
-(id)errorResolverForItem:(id)item;
-(id)copyRawItemAtIndex:(unsigned)index;
-(unsigned)numberOfPaths;
-(unsigned)itemCount;
-(void)dealloc;
-(id)init;
@end

