/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MusicQueryDataSource.h"
#import "Music~ipad-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface MusicPodcastTracksDataSource : MusicQueryDataSource {
	NSArray* _tracks;
}
-(id)playbackContextForIndex:(unsigned)index;
-(void)invalidate;
-(id)entities;
-(void)dealloc;
@end

