/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SSDownloadManagerObserver <NSObject>
@optional
-(void)downloadManagerNetworkUsageDidChange:(id)downloadManagerNetworkUsage;
-(void)downloadManagerDownloadsDidChange:(id)downloadManagerDownloads;
-(void)downloadManagerActiveDownloadsDidChange:(id)downloadManagerActiveDownloads;
-(void)downloadManager:(id)manager downloadStatesDidChange:(id)downloadStates;
@end

