/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIPageControllerDelegate <NSObject>
@optional
-(void)pageControllerDidEndPaging:(id)pageController;
-(void)pageControllerWillBeginPaging:(id)pageController;
-(id)pageController:(id)controller viewControllerRightOfController:(id)controller2;
-(id)pageController:(id)controller viewControllerLeftOfController:(id)controller2;
-(id)pageController:(id)controller viewControllerAtIndex:(int)index;
@end

