#!/bin/sh
if [[ $1 == remove ]]; then
	if [ -f /var/mobile/Library/Preferences/com.autopear.lyricsforipad.plist ]; then
		rm -f /var/mobile/Library/Preferences/com.autopear.lyricsforipad.plist
	fi
fi
exit 0
